# Generated by Django 4.1.3 on 2022-12-12 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpotifyMusic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created_at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated_at"
                    ),
                ),
                ("music_name", models.CharField(max_length=256)),
                ("music_external_url", models.URLField(max_length=256)),
                ("music_preview_url", models.URLField(max_length=256)),
                ("artist_name", models.CharField(max_length=256)),
                ("artist_external_url", models.URLField(max_length=256)),
                ("album_name", models.CharField(max_length=256)),
                ("album_image_url", models.URLField(max_length=256)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.project"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
