# Generated by Django 4.1.4 on 2022-12-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_message_messageimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="top_image_url",
            field=models.URLField(default="", max_length=256),
        ),
        migrations.AddField(
            model_name="project",
            name="top_text",
            field=models.CharField(default="", max_length=32),
        ),
    ]
