# Generated by Django 4.1.4 on 2022-12-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_project_top_image_url_project_top_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="spotify_uri",
            field=models.CharField(
                default="spotify:album:6uqewERWZ1vzfCcin1zFIp", max_length=256
            ),
        ),
        migrations.DeleteModel(
            name="SpotifyMusic",
        ),
    ]
