# Generated by Django 4.1.4 on 2022-12-17 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_project_spotify_uri_delete_spotifymusic"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_publish",
            field=models.BooleanField(default=False),
        ),
    ]
